version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: energy-postgres
    environment:
      POSTGRES_DB: energydb
      POSTGRES_USER: energy
      POSTGRES_PASSWORD: energy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: energy-rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: energy
      RABBITMQ_DEFAULT_PASS: energy

volumes:
  postgres_data:
