spring:
  datasource:
    url: jdbc:postgresql://energy-postgres:5432/energydb
    username: energy
    password: energy
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
