spring:
  datasource:
    url: jdbc:postgresql://energy-postgres:5432/energydb
    username: energy
    password: energy
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: energy-rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 8084
